"""update

Revision ID: 525999fd6d93
Revises: 37855cc0df3e
Create Date: 2024-05-23 18:28:42.912027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525999fd6d93'
down_revision: Union[str, None] = '37855cc0df3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'middle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
