"""not null fields

Revision ID: 8be932f47606
Revises: efd4c7ee4080
Create Date: 2024-05-23 19:36:23.338483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be932f47606'
down_revision: Union[str, None] = 'efd4c7ee4080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salaries', 'salary_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('salaries', 'next_raise_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salaries', 'next_raise_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('salaries', 'salary_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
